minisatip: Switch to cmkae build system and reinstate to feed
Stacktrace isn't supported right now, require gcc update or patch.
So this was also the case before the transition to Cmake.
Drop it (for now).

/home/hains/openpli-oe-core/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/minisatip/
1.0d+git/git/src/utils.cpp: In function 'void print_trace()':
| /home/hains/openpli-oe-core/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/minisatip/
1.0d+git/git/src/utils.cpp:230:16: error: 'stacktrace' in namespace 'std' does not name a type
|   230 |     const std::stacktrace trace = std::stacktrace::current();
|       |                ^~~~~~~~~~